# client/Dockerfile
FROM node:18-alpine

WORKDIR /client

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Use nginx to serve the built app
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
