version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "5173:80"  # External:Internal
    depends_on:
      - api
      - data

  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  data:
    build: ./data
    ports:
      - "8000:8000"
    environment:
      - ENV=production
